name: ✅Feature PR Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop


jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore DotNet Tools
      run: dotnet tool restore
    - name: Run Feature PR Status Check
      run: dotnet cicd FeaturePRStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
