name: ✅Feature PR Status Check


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop


jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Feature PR Status Check
      run: ./build.cmd FeaturePRStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
