name: ✅Hot Fix PR Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - master


jobs:
  build_project:
    if: contains(github.ref, 'refs/pull') && startsWith(github.head_ref, 'hotfix/')
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore DotNet Tools
      run: dotnet tool restore
    - name: Run Build Status Check
      run: dotnet cicd HotFixPRStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
