name: ✅Preview Feature PR Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - preview/v*.*.*-preview.*


jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Feature PR Status Check
      run: ./build.cmd PreviewFeaturePRStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
