name: 🚀Preview Release


on:
  workflow_dispatch:


jobs:
  preview_release:
    name: Preview Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Preview Release
      run: ./build.cmd PreviewRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NugetOrgApiKey: ${{ secrets.NUGET_ORG_API_KEY }}
        TwitterConsumerApiKey: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TwitterConsumerApiSecret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        TwitterAccessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TwitterAccessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
