name: ✅Production Release PR Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - master


jobs:
  prod_release_pr_status_check:
    name: Production Release PR Status Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore DotNet Tools
      run: dotnet tool restore
    - name: Run Production Release PR Status Check
      run: dotnet cicd ProdReleasePRStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
