name: ✅Unit Test Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - preview/v*.*.*-preview.*
      - release/v*.*.*
      - master

jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore DotNet Tools
      run: dotnet tool restore
    - name: Run Unit Test Status Check
      run: dotnet cicd UnitTestStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
